[package]
name = "ara2-bridge-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Safe ARA plug-in authoring runtime"
license.workspace = true
repository.workspace = true

[dependencies]
ara2-bridge-core = { path = "../ara2-bridge-core", version = "=0.3.0" }
ara2-bridge-sys = { path = "../ara2-bridge-sys", version = "=0.3.0" }
bitflags.workspace = true

[dev-dependencies]
ara2-bridge-companion = { path = "../ara2-bridge-companion", version = "=0.3.0" }
