use std::path::Path;
use std::process::Command;

const VERSION: &str = "0.3.0";
const REPOSITORY: &str = "https://github.com/Celemony/ARA_API";
const COMMIT: &str = "65ec5c43b943a48cb5446f448a0492db6af8534b";

fn root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap()
}

fn derivative() -> String {
    format!(
        "// DO NOT EDIT: generated by ara2-bridge xtask {VERSION}.\n\
         // Source repository: {REPOSITORY}\n\
         // Source tag: releases/2.3.0\n\
         // Normative ARA API commit: {COMMIT}\n\
         // Generator: ara2-bridge xtask {VERSION}\n\
         // SPDX-License-Identifier: Apache-2.0\n"
    )
}

#[test]
fn release_help_is_registered() {
    xtask::run(["release".to_owned(), "--help".to_owned()]).unwrap();
}

#[test]
fn ci_attestation_is_not_a_release_command() {
    for command in ["import-evidence", "verify"] {
        let error = xtask::run(["release".to_owned(), command.to_owned()]).unwrap_err();
        assert_eq!(error, format!("unknown release command: {command}"));
    }
}

#[test]
fn invalid_release_version_is_rejected() {
    let error = xtask::run([
        "release".to_owned(),
        "verify-source-inputs".to_owned(),
        "--version".to_owned(),
        "0.2".to_owned(),
    ])
    .unwrap_err();
    assert!(error.contains("0.3.0"), "{error}");
}

#[test]
fn generated_derivative_requires_every_provenance_field() {
    let valid = derivative();
    xtask::release::validate_generated_derivative(&valid).unwrap();
    for missing in [
        "DO NOT EDIT",
        "Source repository:",
        "Source tag:",
        "Normative ARA API commit:",
        "Generator: ara2-bridge xtask 0.3.0",
        "SPDX-License-Identifier: Apache-2.0",
    ] {
        let invalid = valid.replace(missing, "removed");
        let error = xtask::release::validate_generated_derivative(&invalid).unwrap_err();
        assert!(error.contains(missing), "{missing}: {error}");
    }
    for (expected, wrong) in [
        (REPOSITORY, "https://example.invalid/ARA_API"),
        ("releases/2.3.0", "releases/2.2.0"),
        (COMMIT, "0000000000000000000000000000000000000000"),
        (
            "Generator: ara2-bridge xtask 0.3.0",
            "Generator: unknown 9.9.9",
        ),
        (
            "SPDX-License-Identifier: Apache-2.0",
            "SPDX-License-Identifier: NONE",
        ),
    ] {
        let invalid = valid.replace(expected, wrong);
        assert!(
            xtask::release::validate_generated_derivative(&invalid).is_err(),
            "accepted mismatched provenance {wrong}"
        );
    }
}

#[test]
fn packaged_manifest_requires_exact_release_identity_and_sibling_versions() {
    let valid = r#"
[package]
name = "ara2-bridge-plugin"
version = "0.3.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
repository = "https://github.com/entrepeneur4lyf/ara2-bridge"

[dependencies.ara2-bridge-core]
version = "=0.3.0"
"#;
    xtask::release::validate_packaged_manifest(valid, "ara2-bridge-plugin").unwrap();
    for (expected, wrong) in [
        ("name = \"ara2-bridge-plugin\"", "name = \"wrong\""),
        ("version = \"0.3.0\"", "version = \"0.1.0\""),
        ("rust-version = \"1.82\"", "rust-version = \"1.90\""),
        ("license = \"MIT OR Apache-2.0\"", "license = \"NONE\""),
        (
            "repository = \"https://github.com/entrepeneur4lyf/ara2-bridge\"",
            "repository = \"https://example.invalid\"",
        ),
        ("version = \"=0.3.0\"", "version = \"0.2\""),
    ] {
        let invalid = valid.replacen(expected, wrong, 1);
        assert!(
            xtask::release::validate_packaged_manifest(&invalid, "ara2-bridge-plugin").is_err(),
            "accepted invalid package metadata: {wrong}"
        );
    }
}

#[test]
fn checked_in_source_recipe_is_complete() {
    xtask::release::verify_recipe(root(), &root().join("docs/releases/source-bundle.toml"))
        .unwrap();
}

#[cfg(not(windows))]
#[test]
fn release_api_audit_passes_on_candidate_inputs() {
    let root = root();
    if !root
        .join(".third-party/ARA_SDK/ARA_API/ARAInterface.h")
        .is_file()
        || !root.join(".third-party/ARA_SDK/.git").exists()
    {
        eprintln!("skipping release API audit without the maintainer ARA SDK checkout");
        return;
    }
    xtask::release::audit_api(root).unwrap();
}

#[test]
fn release_license_audit_passes_on_candidate_inputs() {
    xtask::release::audit_licenses(root()).unwrap();
}

#[cfg(windows)]
#[test]
fn release_api_audit_requires_a_canonical_generation_host() {
    let error = xtask::release::audit_api(root()).unwrap_err();
    assert!(
        error.contains("binding generation is not supported on Windows"),
        "{error}"
    );
}

#[test]
fn source_bundle_is_deterministic_and_builds_offline() {
    let temp = tempfile::tempdir().unwrap();
    let first = temp.path().join("first.tar.zst");
    let second = temp.path().join("second.tar.zst");

    xtask::release::create_source_bundle(root(), &first, true).unwrap();
    xtask::release::create_source_bundle(root(), &second, true).unwrap();
    assert_eq!(
        std::fs::read(&first).unwrap(),
        std::fs::read(&second).unwrap()
    );
    xtask::release::verify_source_bundle(&first).unwrap();
}

#[test]
fn source_bundle_clean_candidate_gate_rejects_a_dirty_tree() {
    let repository = tempfile::tempdir().unwrap();
    let git = |args: &[&str]| {
        let status = Command::new("git")
            .current_dir(repository.path())
            .args(args)
            .status()
            .unwrap();
        assert!(status.success(), "git {args:?} failed");
    };
    git(&["init", "--quiet"]);
    git(&["config", "user.name", "ARA2 Bridge Test"]);
    git(&["config", "user.email", "test@ara2-bridge.invalid"]);
    std::fs::write(repository.path().join("tracked.txt"), "clean\n").unwrap();
    git(&["add", "tracked.txt"]);
    git(&["commit", "--quiet", "-m", "test fixture"]);
    std::fs::write(repository.path().join("tracked.txt"), "dirty\n").unwrap();

    let error = xtask::release::verify_clean_candidate(repository.path()).unwrap_err();
    assert!(error.contains("clean tracked candidate tree"), "{error}");
}

#[test]
fn verify_source_bundle_command_rejects_a_missing_archive() {
    let missing = tempfile::tempdir().unwrap().path().join("missing.tar.zst");
    let error = xtask::run([
        "release".to_owned(),
        "verify-source-bundle".to_owned(),
        "--bundle".to_owned(),
        missing.display().to_string(),
    ])
    .unwrap_err();
    assert!(error.contains("cannot open"), "{error}");
}
