use std::path::Path;

const VERSION: &str = "0.2.0-alpha.1";
const REPOSITORY: &str = "https://github.com/Celemony/ARA_API";
const COMMIT: &str = "65ec5c43b943a48cb5446f448a0492db6af8534b";

fn root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap()
}

fn derivative() -> String {
    format!(
        "// DO NOT EDIT: generated by ara2-bridge xtask {VERSION}.\n\
         // Source repository: {REPOSITORY}\n\
         // Source tag: releases/2.3.0\n\
         // Normative ARA API commit: {COMMIT}\n\
         // Generator: ara2-bridge xtask {VERSION}\n\
         // SPDX-License-Identifier: Apache-2.0\n"
    )
}

#[test]
fn release_help_is_registered() {
    xtask::run(["release".to_owned(), "--help".to_owned()]).unwrap();
}

#[test]
fn invalid_release_version_is_rejected() {
    let error = xtask::run([
        "release".to_owned(),
        "verify-source-inputs".to_owned(),
        "--version".to_owned(),
        "0.2".to_owned(),
    ])
    .unwrap_err();
    assert!(error.contains("0.2.0-alpha.1"), "{error}");
}

#[test]
fn generated_derivative_requires_every_provenance_field() {
    let valid = derivative();
    xtask::release::validate_generated_derivative(&valid).unwrap();
    for missing in [
        "DO NOT EDIT",
        "Source repository:",
        "Source tag:",
        "Normative ARA API commit:",
        "Generator: ara2-bridge xtask 0.2.0-alpha.1",
        "SPDX-License-Identifier: Apache-2.0",
    ] {
        let invalid = valid.replace(missing, "removed");
        let error = xtask::release::validate_generated_derivative(&invalid).unwrap_err();
        assert!(error.contains(missing), "{missing}: {error}");
    }
}

#[test]
fn checked_in_source_recipe_is_complete() {
    xtask::release::verify_recipe(root(), &root().join("docs/releases/source-bundle.toml"))
        .unwrap();
}

#[test]
fn release_audits_pass_on_candidate_inputs() {
    xtask::release::audit_api(root()).unwrap();
    xtask::release::audit_licenses(root()).unwrap();
}

#[test]
fn evidence_receipt_rejects_each_identity_mismatch() {
    let digest = "a".repeat(64);
    let valid = serde_json::json!({
        "schema": 1,
        "repository": "entrepeneur4lyf/ara2-bridge",
        "commit": COMMIT,
        "subject_sha256": digest,
        "issuer": "https://token.actions.githubusercontent.com",
        "workflow": ".github/workflows/release.yml",
        "verified_by": "gh attestation verify"
    });
    xtask::release::validate_evidence_receipt(&valid, COMMIT, &"a".repeat(64)).unwrap();
    for (field, wrong) in [
        ("repository", "wrong/repository"),
        ("commit", "0000000000000000000000000000000000000000"),
        (
            "subject_sha256",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        ),
        ("issuer", "https://example.invalid"),
        ("workflow", ".github/workflows/other.yml"),
        ("verified_by", "manual assertion"),
    ] {
        let mut invalid = valid.clone();
        invalid[field] = serde_json::Value::String(wrong.to_owned());
        let error = xtask::release::validate_evidence_receipt(&invalid, COMMIT, &"a".repeat(64))
            .unwrap_err();
        assert!(error.contains(field), "{field}: {error}");
    }
}
