// DO NOT EDIT: generated by ara2-bridge xtask 0.3.0.
// Source repository: https://github.com/Celemony/ARA_API
// Source tag: releases/2.3.0
// Normative ARA API commit: 65ec5c43b943a48cb5446f448a0492db6af8534b
// Generator: ara2-bridge xtask 0.3.0
// SPDX-License-Identifier: Apache-2.0

//! Generated ARA document-controller callback shells and coverage join.

#![allow(
    non_snake_case,
    unused_variables,
    unsafe_op_in_unsafe_fn,
    clippy::undocumented_unsafe_blocks
)]

use ara2_bridge_sys::*;

pub(crate) trait ControllerDelegate {
    fn destroy_document_controller(&mut self) {}
    fn get_factory(&mut self) -> *const ARAFactory {
        ::std::ptr::null()
    }
    fn begin_editing(&mut self) {}
    fn end_editing(&mut self) {}
    fn notify_model_updates(&mut self) {}
    fn begin_restoring_document_from_archive(
        &mut self,
        archiveReaderHostRef: ARAArchiveReaderHostRef,
    ) -> ARABool {
        kARAFalse
    }
    fn end_restoring_document_from_archive(
        &mut self,
        archiveReaderHostRef: ARAArchiveReaderHostRef,
    ) -> ARABool {
        kARAFalse
    }
    fn store_document_to_archive(
        &mut self,
        archiveWriterHostRef: ARAArchiveWriterHostRef,
    ) -> ARABool {
        kARAFalse
    }
    fn update_document_properties(&mut self, properties: *const ARADocumentProperties) {}
    fn create_musical_context(
        &mut self,
        hostRef: ARAMusicalContextHostRef,
        properties: *const ARAMusicalContextProperties,
    ) -> ARAMusicalContextRef {
        ::std::ptr::null_mut()
    }
    fn update_musical_context_properties(
        &mut self,
        musicalContextRef: ARAMusicalContextRef,
        properties: *const ARAMusicalContextProperties,
    ) {
    }
    fn update_musical_context_content(
        &mut self,
        musicalContextRef: ARAMusicalContextRef,
        range: *const ARAContentTimeRange,
        flags: ARAContentUpdateFlags,
    ) {
    }
    fn destroy_musical_context(&mut self, musicalContextRef: ARAMusicalContextRef) {}
    fn create_audio_source(
        &mut self,
        hostRef: ARAAudioSourceHostRef,
        properties: *const ARAAudioSourceProperties,
    ) -> ARAAudioSourceRef {
        ::std::ptr::null_mut()
    }
    fn update_audio_source_properties(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        properties: *const ARAAudioSourceProperties,
    ) {
    }
    fn update_audio_source_content(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        range: *const ARAContentTimeRange,
        flags: ARAContentUpdateFlags,
    ) {
    }
    fn enable_audio_source_samples_access(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        enable: ARABool,
    ) {
    }
    fn deactivate_audio_source_for_undo_history(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        deactivate: ARABool,
    ) {
    }
    fn destroy_audio_source(&mut self, audioSourceRef: ARAAudioSourceRef) {}
    fn create_audio_modification(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        hostRef: ARAAudioModificationHostRef,
        properties: *const ARAAudioModificationProperties,
    ) -> ARAAudioModificationRef {
        ::std::ptr::null_mut()
    }
    fn clone_audio_modification(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        hostRef: ARAAudioModificationHostRef,
        properties: *const ARAAudioModificationProperties,
    ) -> ARAAudioModificationRef {
        ::std::ptr::null_mut()
    }
    fn update_audio_modification_properties(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        properties: *const ARAAudioModificationProperties,
    ) {
    }
    fn deactivate_audio_modification_for_undo_history(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        deactivate: ARABool,
    ) {
    }
    fn destroy_audio_modification(&mut self, audioModificationRef: ARAAudioModificationRef) {}
    fn create_playback_region(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        hostRef: ARAPlaybackRegionHostRef,
        properties: *const ARAPlaybackRegionProperties,
    ) -> ARAPlaybackRegionRef {
        ::std::ptr::null_mut()
    }
    fn update_playback_region_properties(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        properties: *const ARAPlaybackRegionProperties,
    ) {
    }
    fn destroy_playback_region(&mut self, playbackRegionRef: ARAPlaybackRegionRef) {}
    fn is_audio_source_content_available(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentType: ARAContentType,
    ) -> ARABool {
        kARAFalse
    }
    fn is_audio_source_content_analysis_incomplete(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentType: ARAContentType,
    ) -> ARABool {
        kARAFalse
    }
    fn request_audio_source_content_analysis(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentTypesCount: ARASize,
        contentTypes: *const ARAContentType,
    ) {
    }
    fn get_audio_source_content_grade(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentType: ARAContentType,
    ) -> ARAContentGrade {
        0
    }
    fn create_audio_source_content_reader(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentType: ARAContentType,
        range: *const ARAContentTimeRange,
    ) -> ARAContentReaderRef {
        ::std::ptr::null_mut()
    }
    fn is_audio_modification_content_available(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        contentType: ARAContentType,
    ) -> ARABool {
        kARAFalse
    }
    fn get_audio_modification_content_grade(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        contentType: ARAContentType,
    ) -> ARAContentGrade {
        0
    }
    fn create_audio_modification_content_reader(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        contentType: ARAContentType,
        range: *const ARAContentTimeRange,
    ) -> ARAContentReaderRef {
        ::std::ptr::null_mut()
    }
    fn is_playback_region_content_available(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        contentType: ARAContentType,
    ) -> ARABool {
        kARAFalse
    }
    fn get_playback_region_content_grade(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        contentType: ARAContentType,
    ) -> ARAContentGrade {
        0
    }
    fn create_playback_region_content_reader(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        contentType: ARAContentType,
        range: *const ARAContentTimeRange,
    ) -> ARAContentReaderRef {
        ::std::ptr::null_mut()
    }
    fn get_content_reader_event_count(
        &mut self,
        contentReaderRef: ARAContentReaderRef,
    ) -> ARAInt32 {
        0
    }
    fn get_content_reader_data_for_event(
        &mut self,
        contentReaderRef: ARAContentReaderRef,
        eventIndex: ARAInt32,
    ) -> *const ::std::os::raw::c_void {
        ::std::ptr::null()
    }
    fn destroy_content_reader(&mut self, contentReaderRef: ARAContentReaderRef) {}
    fn create_region_sequence(
        &mut self,
        hostRef: ARARegionSequenceHostRef,
        properties: *const ARARegionSequenceProperties,
    ) -> ARARegionSequenceRef {
        ::std::ptr::null_mut()
    }
    fn update_region_sequence_properties(
        &mut self,
        regionSequenceRef: ARARegionSequenceRef,
        properties: *const ARARegionSequenceProperties,
    ) {
    }
    fn destroy_region_sequence(&mut self, regionSequenceRef: ARARegionSequenceRef) {}
    fn get_playback_region_head_and_tail_time(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        headTime: *mut ARATimeDuration,
        tailTime: *mut ARATimeDuration,
    ) {
    }
    fn restore_objects_from_archive(
        &mut self,
        archiveReaderHostRef: ARAArchiveReaderHostRef,
        filter: *const ARARestoreObjectsFilter,
    ) -> ARABool {
        kARAFalse
    }
    fn store_objects_to_archive(
        &mut self,
        archiveWriterHostRef: ARAArchiveWriterHostRef,
        filter: *const ARAStoreObjectsFilter,
    ) -> ARABool {
        kARAFalse
    }
    fn get_processing_algorithms_count(&mut self) -> ARAInt32 {
        0
    }
    fn get_processing_algorithm_properties(
        &mut self,
        algorithmIndex: ARAInt32,
    ) -> *const ARAProcessingAlgorithmProperties {
        ::std::ptr::null()
    }
    fn get_processing_algorithm_for_audio_source(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
    ) -> ARAInt32 {
        0
    }
    fn request_processing_algorithm_for_audio_source(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        algorithmIndex: ARAInt32,
    ) {
    }
    fn is_licensed_for_capabilities(
        &mut self,
        runModalActivationDialogIfNeeded: ARABool,
        contentTypesCount: ARASize,
        contentTypes: *const ARAContentType,
        transformationFlags: ARAPlaybackTransformationFlags,
    ) -> ARABool {
        kARATrue
    }
    fn store_audio_source_to_audio_file_chunk(
        &mut self,
        archiveWriterHostRef: ARAArchiveWriterHostRef,
        audioSourceRef: ARAAudioSourceRef,
        documentArchiveID: *mut ARAPersistentID,
        openAutomatically: *mut ARABool,
    ) -> ARABool {
        kARAFalse
    }
    fn is_audio_modification_preserving_audio_source_signal(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
    ) -> ARABool {
        kARAFalse
    }
}

pub(crate) unsafe extern "C" fn destroy_document_controller(
    controllerRef: ARADocumentControllerRef,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.destroy_document_controller()
    });
    super::callbacks::destroy_controller_ref(controllerRef)
}

pub(crate) unsafe extern "C" fn get_factory(
    controllerRef: ARADocumentControllerRef,
) -> *const ARAFactory {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null(), |delegate| {
        delegate.get_factory()
    })
}

pub(crate) unsafe extern "C" fn begin_editing(controllerRef: ARADocumentControllerRef) {
    super::callbacks::dispatch(controllerRef, (), |delegate| delegate.begin_editing())
}

pub(crate) unsafe extern "C" fn end_editing(controllerRef: ARADocumentControllerRef) {
    super::callbacks::dispatch(controllerRef, (), |delegate| delegate.end_editing())
}

pub(crate) unsafe extern "C" fn notify_model_updates(controllerRef: ARADocumentControllerRef) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.notify_model_updates()
    })
}

pub(crate) unsafe extern "C" fn begin_restoring_document_from_archive(
    controllerRef: ARADocumentControllerRef,
    archiveReaderHostRef: ARAArchiveReaderHostRef,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.begin_restoring_document_from_archive(archiveReaderHostRef)
    })
}

pub(crate) unsafe extern "C" fn end_restoring_document_from_archive(
    controllerRef: ARADocumentControllerRef,
    archiveReaderHostRef: ARAArchiveReaderHostRef,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.end_restoring_document_from_archive(archiveReaderHostRef)
    })
}

pub(crate) unsafe extern "C" fn store_document_to_archive(
    controllerRef: ARADocumentControllerRef,
    archiveWriterHostRef: ARAArchiveWriterHostRef,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.store_document_to_archive(archiveWriterHostRef)
    })
}

pub(crate) unsafe extern "C" fn update_document_properties(
    controllerRef: ARADocumentControllerRef,
    properties: *const ARADocumentProperties,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.update_document_properties(properties)
    })
}

pub(crate) unsafe extern "C" fn create_musical_context(
    controllerRef: ARADocumentControllerRef,
    hostRef: ARAMusicalContextHostRef,
    properties: *const ARAMusicalContextProperties,
) -> ARAMusicalContextRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.create_musical_context(hostRef, properties)
    })
}

pub(crate) unsafe extern "C" fn update_musical_context_properties(
    controllerRef: ARADocumentControllerRef,
    musicalContextRef: ARAMusicalContextRef,
    properties: *const ARAMusicalContextProperties,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.update_musical_context_properties(musicalContextRef, properties)
    })
}

pub(crate) unsafe extern "C" fn update_musical_context_content(
    controllerRef: ARADocumentControllerRef,
    musicalContextRef: ARAMusicalContextRef,
    range: *const ARAContentTimeRange,
    flags: ARAContentUpdateFlags,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.update_musical_context_content(musicalContextRef, range, flags)
    })
}

pub(crate) unsafe extern "C" fn destroy_musical_context(
    controllerRef: ARADocumentControllerRef,
    musicalContextRef: ARAMusicalContextRef,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.destroy_musical_context(musicalContextRef)
    })
}

pub(crate) unsafe extern "C" fn create_audio_source(
    controllerRef: ARADocumentControllerRef,
    hostRef: ARAAudioSourceHostRef,
    properties: *const ARAAudioSourceProperties,
) -> ARAAudioSourceRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.create_audio_source(hostRef, properties)
    })
}

pub(crate) unsafe extern "C" fn update_audio_source_properties(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    properties: *const ARAAudioSourceProperties,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.update_audio_source_properties(audioSourceRef, properties)
    })
}

pub(crate) unsafe extern "C" fn update_audio_source_content(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    range: *const ARAContentTimeRange,
    flags: ARAContentUpdateFlags,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.update_audio_source_content(audioSourceRef, range, flags)
    })
}

pub(crate) unsafe extern "C" fn enable_audio_source_samples_access(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    enable: ARABool,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.enable_audio_source_samples_access(audioSourceRef, enable)
    })
}

pub(crate) unsafe extern "C" fn deactivate_audio_source_for_undo_history(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    deactivate: ARABool,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.deactivate_audio_source_for_undo_history(audioSourceRef, deactivate)
    })
}

pub(crate) unsafe extern "C" fn destroy_audio_source(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.destroy_audio_source(audioSourceRef)
    })
}

pub(crate) unsafe extern "C" fn create_audio_modification(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    hostRef: ARAAudioModificationHostRef,
    properties: *const ARAAudioModificationProperties,
) -> ARAAudioModificationRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.create_audio_modification(audioSourceRef, hostRef, properties)
    })
}

pub(crate) unsafe extern "C" fn clone_audio_modification(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    hostRef: ARAAudioModificationHostRef,
    properties: *const ARAAudioModificationProperties,
) -> ARAAudioModificationRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.clone_audio_modification(audioModificationRef, hostRef, properties)
    })
}

pub(crate) unsafe extern "C" fn update_audio_modification_properties(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    properties: *const ARAAudioModificationProperties,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.update_audio_modification_properties(audioModificationRef, properties)
    })
}

pub(crate) unsafe extern "C" fn deactivate_audio_modification_for_undo_history(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    deactivate: ARABool,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.deactivate_audio_modification_for_undo_history(audioModificationRef, deactivate)
    })
}

pub(crate) unsafe extern "C" fn destroy_audio_modification(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.destroy_audio_modification(audioModificationRef)
    })
}

pub(crate) unsafe extern "C" fn create_playback_region(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    hostRef: ARAPlaybackRegionHostRef,
    properties: *const ARAPlaybackRegionProperties,
) -> ARAPlaybackRegionRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.create_playback_region(audioModificationRef, hostRef, properties)
    })
}

pub(crate) unsafe extern "C" fn update_playback_region_properties(
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    properties: *const ARAPlaybackRegionProperties,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.update_playback_region_properties(playbackRegionRef, properties)
    })
}

pub(crate) unsafe extern "C" fn destroy_playback_region(
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.destroy_playback_region(playbackRegionRef)
    })
}

pub(crate) unsafe extern "C" fn is_audio_source_content_available(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentType: ARAContentType,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.is_audio_source_content_available(audioSourceRef, contentType)
    })
}

pub(crate) unsafe extern "C" fn is_audio_source_content_analysis_incomplete(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentType: ARAContentType,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.is_audio_source_content_analysis_incomplete(audioSourceRef, contentType)
    })
}

pub(crate) unsafe extern "C" fn request_audio_source_content_analysis(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentTypesCount: ARASize,
    contentTypes: *const ARAContentType,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.request_audio_source_content_analysis(
            audioSourceRef,
            contentTypesCount,
            contentTypes,
        )
    })
}

pub(crate) unsafe extern "C" fn get_audio_source_content_grade(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentType: ARAContentType,
) -> ARAContentGrade {
    super::callbacks::dispatch(controllerRef, 0, |delegate| {
        delegate.get_audio_source_content_grade(audioSourceRef, contentType)
    })
}

pub(crate) unsafe extern "C" fn create_audio_source_content_reader(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentType: ARAContentType,
    range: *const ARAContentTimeRange,
) -> ARAContentReaderRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.create_audio_source_content_reader(audioSourceRef, contentType, range)
    })
}

pub(crate) unsafe extern "C" fn is_audio_modification_content_available(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    contentType: ARAContentType,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.is_audio_modification_content_available(audioModificationRef, contentType)
    })
}

pub(crate) unsafe extern "C" fn get_audio_modification_content_grade(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    contentType: ARAContentType,
) -> ARAContentGrade {
    super::callbacks::dispatch(controllerRef, 0, |delegate| {
        delegate.get_audio_modification_content_grade(audioModificationRef, contentType)
    })
}

pub(crate) unsafe extern "C" fn create_audio_modification_content_reader(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    contentType: ARAContentType,
    range: *const ARAContentTimeRange,
) -> ARAContentReaderRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.create_audio_modification_content_reader(audioModificationRef, contentType, range)
    })
}

pub(crate) unsafe extern "C" fn is_playback_region_content_available(
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    contentType: ARAContentType,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.is_playback_region_content_available(playbackRegionRef, contentType)
    })
}

pub(crate) unsafe extern "C" fn get_playback_region_content_grade(
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    contentType: ARAContentType,
) -> ARAContentGrade {
    super::callbacks::dispatch(controllerRef, 0, |delegate| {
        delegate.get_playback_region_content_grade(playbackRegionRef, contentType)
    })
}

pub(crate) unsafe extern "C" fn create_playback_region_content_reader(
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    contentType: ARAContentType,
    range: *const ARAContentTimeRange,
) -> ARAContentReaderRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.create_playback_region_content_reader(playbackRegionRef, contentType, range)
    })
}

pub(crate) unsafe extern "C" fn get_content_reader_event_count(
    controllerRef: ARADocumentControllerRef,
    contentReaderRef: ARAContentReaderRef,
) -> ARAInt32 {
    super::callbacks::dispatch(controllerRef, 0, |delegate| {
        delegate.get_content_reader_event_count(contentReaderRef)
    })
}

pub(crate) unsafe extern "C" fn get_content_reader_data_for_event(
    controllerRef: ARADocumentControllerRef,
    contentReaderRef: ARAContentReaderRef,
    eventIndex: ARAInt32,
) -> *const ::std::os::raw::c_void {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null(), |delegate| {
        delegate.get_content_reader_data_for_event(contentReaderRef, eventIndex)
    })
}

pub(crate) unsafe extern "C" fn destroy_content_reader(
    controllerRef: ARADocumentControllerRef,
    contentReaderRef: ARAContentReaderRef,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.destroy_content_reader(contentReaderRef)
    })
}

pub(crate) unsafe extern "C" fn create_region_sequence(
    controllerRef: ARADocumentControllerRef,
    hostRef: ARARegionSequenceHostRef,
    properties: *const ARARegionSequenceProperties,
) -> ARARegionSequenceRef {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null_mut(), |delegate| {
        delegate.create_region_sequence(hostRef, properties)
    })
}

pub(crate) unsafe extern "C" fn update_region_sequence_properties(
    controllerRef: ARADocumentControllerRef,
    regionSequenceRef: ARARegionSequenceRef,
    properties: *const ARARegionSequenceProperties,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.update_region_sequence_properties(regionSequenceRef, properties)
    })
}

pub(crate) unsafe extern "C" fn destroy_region_sequence(
    controllerRef: ARADocumentControllerRef,
    regionSequenceRef: ARARegionSequenceRef,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.destroy_region_sequence(regionSequenceRef)
    })
}

pub(crate) unsafe extern "C" fn get_playback_region_head_and_tail_time(
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    headTime: *mut ARATimeDuration,
    tailTime: *mut ARATimeDuration,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.get_playback_region_head_and_tail_time(playbackRegionRef, headTime, tailTime)
    })
}

pub(crate) unsafe extern "C" fn restore_objects_from_archive(
    controllerRef: ARADocumentControllerRef,
    archiveReaderHostRef: ARAArchiveReaderHostRef,
    filter: *const ARARestoreObjectsFilter,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.restore_objects_from_archive(archiveReaderHostRef, filter)
    })
}

pub(crate) unsafe extern "C" fn store_objects_to_archive(
    controllerRef: ARADocumentControllerRef,
    archiveWriterHostRef: ARAArchiveWriterHostRef,
    filter: *const ARAStoreObjectsFilter,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.store_objects_to_archive(archiveWriterHostRef, filter)
    })
}

pub(crate) unsafe extern "C" fn get_processing_algorithms_count(
    controllerRef: ARADocumentControllerRef,
) -> ARAInt32 {
    super::callbacks::dispatch(controllerRef, 0, |delegate| {
        delegate.get_processing_algorithms_count()
    })
}

pub(crate) unsafe extern "C" fn get_processing_algorithm_properties(
    controllerRef: ARADocumentControllerRef,
    algorithmIndex: ARAInt32,
) -> *const ARAProcessingAlgorithmProperties {
    super::callbacks::dispatch(controllerRef, ::std::ptr::null(), |delegate| {
        delegate.get_processing_algorithm_properties(algorithmIndex)
    })
}

pub(crate) unsafe extern "C" fn get_processing_algorithm_for_audio_source(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
) -> ARAInt32 {
    super::callbacks::dispatch(controllerRef, 0, |delegate| {
        delegate.get_processing_algorithm_for_audio_source(audioSourceRef)
    })
}

pub(crate) unsafe extern "C" fn request_processing_algorithm_for_audio_source(
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    algorithmIndex: ARAInt32,
) {
    super::callbacks::dispatch(controllerRef, (), |delegate| {
        delegate.request_processing_algorithm_for_audio_source(audioSourceRef, algorithmIndex)
    })
}

pub(crate) unsafe extern "C" fn is_licensed_for_capabilities(
    controllerRef: ARADocumentControllerRef,
    runModalActivationDialogIfNeeded: ARABool,
    contentTypesCount: ARASize,
    contentTypes: *const ARAContentType,
    transformationFlags: ARAPlaybackTransformationFlags,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARATrue, |delegate| {
        delegate.is_licensed_for_capabilities(
            runModalActivationDialogIfNeeded,
            contentTypesCount,
            contentTypes,
            transformationFlags,
        )
    })
}

pub(crate) unsafe extern "C" fn store_audio_source_to_audio_file_chunk(
    controllerRef: ARADocumentControllerRef,
    archiveWriterHostRef: ARAArchiveWriterHostRef,
    audioSourceRef: ARAAudioSourceRef,
    documentArchiveID: *mut ARAPersistentID,
    openAutomatically: *mut ARABool,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.store_audio_source_to_audio_file_chunk(
            archiveWriterHostRef,
            audioSourceRef,
            documentArchiveID,
            openAutomatically,
        )
    })
}

pub(crate) unsafe extern "C" fn is_audio_modification_preserving_audio_source_signal(
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
) -> ARABool {
    super::callbacks::dispatch(controllerRef, kARAFalse, |delegate| {
        delegate.is_audio_modification_preserving_audio_source_signal(audioModificationRef)
    })
}

pub(crate) fn raw_interface(struct_size: usize) -> ARADocumentControllerInterface {
    ARADocumentControllerInterface {
        structSize: struct_size,
        destroyDocumentController: Some(destroy_document_controller),
        getFactory: Some(get_factory),
        beginEditing: Some(begin_editing),
        endEditing: Some(end_editing),
        notifyModelUpdates: Some(notify_model_updates),
        beginRestoringDocumentFromArchive: Some(begin_restoring_document_from_archive),
        endRestoringDocumentFromArchive: Some(end_restoring_document_from_archive),
        storeDocumentToArchive: Some(store_document_to_archive),
        updateDocumentProperties: Some(update_document_properties),
        createMusicalContext: Some(create_musical_context),
        updateMusicalContextProperties: Some(update_musical_context_properties),
        updateMusicalContextContent: Some(update_musical_context_content),
        destroyMusicalContext: Some(destroy_musical_context),
        createAudioSource: Some(create_audio_source),
        updateAudioSourceProperties: Some(update_audio_source_properties),
        updateAudioSourceContent: Some(update_audio_source_content),
        enableAudioSourceSamplesAccess: Some(enable_audio_source_samples_access),
        deactivateAudioSourceForUndoHistory: Some(deactivate_audio_source_for_undo_history),
        destroyAudioSource: Some(destroy_audio_source),
        createAudioModification: Some(create_audio_modification),
        cloneAudioModification: Some(clone_audio_modification),
        updateAudioModificationProperties: Some(update_audio_modification_properties),
        deactivateAudioModificationForUndoHistory: Some(
            deactivate_audio_modification_for_undo_history,
        ),
        destroyAudioModification: Some(destroy_audio_modification),
        createPlaybackRegion: Some(create_playback_region),
        updatePlaybackRegionProperties: Some(update_playback_region_properties),
        destroyPlaybackRegion: Some(destroy_playback_region),
        isAudioSourceContentAvailable: Some(is_audio_source_content_available),
        isAudioSourceContentAnalysisIncomplete: Some(is_audio_source_content_analysis_incomplete),
        requestAudioSourceContentAnalysis: Some(request_audio_source_content_analysis),
        getAudioSourceContentGrade: Some(get_audio_source_content_grade),
        createAudioSourceContentReader: Some(create_audio_source_content_reader),
        isAudioModificationContentAvailable: Some(is_audio_modification_content_available),
        getAudioModificationContentGrade: Some(get_audio_modification_content_grade),
        createAudioModificationContentReader: Some(create_audio_modification_content_reader),
        isPlaybackRegionContentAvailable: Some(is_playback_region_content_available),
        getPlaybackRegionContentGrade: Some(get_playback_region_content_grade),
        createPlaybackRegionContentReader: Some(create_playback_region_content_reader),
        getContentReaderEventCount: Some(get_content_reader_event_count),
        getContentReaderDataForEvent: Some(get_content_reader_data_for_event),
        destroyContentReader: Some(destroy_content_reader),
        createRegionSequence: Some(create_region_sequence),
        updateRegionSequenceProperties: Some(update_region_sequence_properties),
        destroyRegionSequence: Some(destroy_region_sequence),
        getPlaybackRegionHeadAndTailTime: Some(get_playback_region_head_and_tail_time),
        restoreObjectsFromArchive: Some(restore_objects_from_archive),
        storeObjectsToArchive: Some(store_objects_to_archive),
        getProcessingAlgorithmsCount: Some(get_processing_algorithms_count),
        getProcessingAlgorithmProperties: Some(get_processing_algorithm_properties),
        getProcessingAlgorithmForAudioSource: Some(get_processing_algorithm_for_audio_source),
        requestProcessingAlgorithmForAudioSource: Some(
            request_processing_algorithm_for_audio_source,
        ),
        isLicensedForCapabilities: Some(is_licensed_for_capabilities),
        storeAudioSourceToAudioFileChunk: Some(store_audio_source_to_audio_file_chunk),
        isAudioModificationPreservingAudioSourceSignal: Some(
            is_audio_modification_preserving_audio_source_signal,
        ),
    }
}

pub(crate) fn represented_callbacks_are_non_null(
    raw: &ARADocumentControllerInterface,
    count: usize,
) -> bool {
    let callbacks = [
        unsafe {
            ::std::ptr::addr_of!(raw.destroyDocumentController)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getFactory)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.beginEditing)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.endEditing)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.notifyModelUpdates)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.beginRestoringDocumentFromArchive)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.endRestoringDocumentFromArchive)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.storeDocumentToArchive)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.updateDocumentProperties)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.createMusicalContext)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.updateMusicalContextProperties)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.updateMusicalContextContent)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.destroyMusicalContext)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.createAudioSource)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.updateAudioSourceProperties)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.updateAudioSourceContent)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.enableAudioSourceSamplesAccess)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.deactivateAudioSourceForUndoHistory)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.destroyAudioSource)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.createAudioModification)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.cloneAudioModification)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.updateAudioModificationProperties)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.deactivateAudioModificationForUndoHistory)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.destroyAudioModification)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.createPlaybackRegion)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.updatePlaybackRegionProperties)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.destroyPlaybackRegion)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.isAudioSourceContentAvailable)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.isAudioSourceContentAnalysisIncomplete)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.requestAudioSourceContentAnalysis)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getAudioSourceContentGrade)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.createAudioSourceContentReader)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.isAudioModificationContentAvailable)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getAudioModificationContentGrade)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.createAudioModificationContentReader)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.isPlaybackRegionContentAvailable)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getPlaybackRegionContentGrade)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.createPlaybackRegionContentReader)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getContentReaderEventCount)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getContentReaderDataForEvent)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.destroyContentReader)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.createRegionSequence)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.updateRegionSequenceProperties)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.destroyRegionSequence)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getPlaybackRegionHeadAndTailTime)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.restoreObjectsFromArchive)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.storeObjectsToArchive)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getProcessingAlgorithmsCount)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getProcessingAlgorithmProperties)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.getProcessingAlgorithmForAudioSource)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.requestProcessingAlgorithmForAudioSource)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.isLicensedForCapabilities)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.storeAudioSourceToAudioFileChunk)
                .read_unaligned()
                .is_some()
        },
        unsafe {
            ::std::ptr::addr_of!(raw.isAudioModificationPreservingAudioSourceSignal)
                .read_unaligned()
                .is_some()
        },
    ];
    callbacks.iter().take(count).all(|present| *present)
}

/// Exact one-to-one join from C callback slots to generated delegates.
pub static PLUGIN_DELEGATES: &[super::callbacks::Delegate] = &[
    super::callbacks::Delegate::new("destroyDocumentController", 0),
    super::callbacks::Delegate::new("getFactory", 1),
    super::callbacks::Delegate::new("beginEditing", 2),
    super::callbacks::Delegate::new("endEditing", 3),
    super::callbacks::Delegate::new("notifyModelUpdates", 4),
    super::callbacks::Delegate::new("beginRestoringDocumentFromArchive", 5),
    super::callbacks::Delegate::new("endRestoringDocumentFromArchive", 6),
    super::callbacks::Delegate::new("storeDocumentToArchive", 7),
    super::callbacks::Delegate::new("updateDocumentProperties", 8),
    super::callbacks::Delegate::new("createMusicalContext", 9),
    super::callbacks::Delegate::new("updateMusicalContextProperties", 10),
    super::callbacks::Delegate::new("updateMusicalContextContent", 11),
    super::callbacks::Delegate::new("destroyMusicalContext", 12),
    super::callbacks::Delegate::new("createAudioSource", 13),
    super::callbacks::Delegate::new("updateAudioSourceProperties", 14),
    super::callbacks::Delegate::new("updateAudioSourceContent", 15),
    super::callbacks::Delegate::new("enableAudioSourceSamplesAccess", 16),
    super::callbacks::Delegate::new("deactivateAudioSourceForUndoHistory", 17),
    super::callbacks::Delegate::new("destroyAudioSource", 18),
    super::callbacks::Delegate::new("createAudioModification", 19),
    super::callbacks::Delegate::new("cloneAudioModification", 20),
    super::callbacks::Delegate::new("updateAudioModificationProperties", 21),
    super::callbacks::Delegate::new("deactivateAudioModificationForUndoHistory", 22),
    super::callbacks::Delegate::new("destroyAudioModification", 23),
    super::callbacks::Delegate::new("createPlaybackRegion", 24),
    super::callbacks::Delegate::new("updatePlaybackRegionProperties", 25),
    super::callbacks::Delegate::new("destroyPlaybackRegion", 26),
    super::callbacks::Delegate::new("isAudioSourceContentAvailable", 27),
    super::callbacks::Delegate::new("isAudioSourceContentAnalysisIncomplete", 28),
    super::callbacks::Delegate::new("requestAudioSourceContentAnalysis", 29),
    super::callbacks::Delegate::new("getAudioSourceContentGrade", 30),
    super::callbacks::Delegate::new("createAudioSourceContentReader", 31),
    super::callbacks::Delegate::new("isAudioModificationContentAvailable", 32),
    super::callbacks::Delegate::new("getAudioModificationContentGrade", 33),
    super::callbacks::Delegate::new("createAudioModificationContentReader", 34),
    super::callbacks::Delegate::new("isPlaybackRegionContentAvailable", 35),
    super::callbacks::Delegate::new("getPlaybackRegionContentGrade", 36),
    super::callbacks::Delegate::new("createPlaybackRegionContentReader", 37),
    super::callbacks::Delegate::new("getContentReaderEventCount", 38),
    super::callbacks::Delegate::new("getContentReaderDataForEvent", 39),
    super::callbacks::Delegate::new("destroyContentReader", 40),
    super::callbacks::Delegate::new("createRegionSequence", 41),
    super::callbacks::Delegate::new("updateRegionSequenceProperties", 42),
    super::callbacks::Delegate::new("destroyRegionSequence", 43),
    super::callbacks::Delegate::new("getPlaybackRegionHeadAndTailTime", 44),
    super::callbacks::Delegate::new("restoreObjectsFromArchive", 45),
    super::callbacks::Delegate::new("storeObjectsToArchive", 46),
    super::callbacks::Delegate::new("getProcessingAlgorithmsCount", 47),
    super::callbacks::Delegate::new("getProcessingAlgorithmProperties", 48),
    super::callbacks::Delegate::new("getProcessingAlgorithmForAudioSource", 49),
    super::callbacks::Delegate::new("requestProcessingAlgorithmForAudioSource", 50),
    super::callbacks::Delegate::new("isLicensedForCapabilities", 51),
    super::callbacks::Delegate::new("storeAudioSourceToAudioFileChunk", 52),
    super::callbacks::Delegate::new("isAudioModificationPreservingAudioSourceSignal", 53),
];

/// Required conformance-test entry for every generated callback slot.
pub static PLUGIN_CONTRACT_TESTS: &[super::callbacks::CallbackContract] = &[
    super::callbacks::CallbackContract::new("destroyDocumentController", 0),
    super::callbacks::CallbackContract::new("getFactory", 1),
    super::callbacks::CallbackContract::new("beginEditing", 2),
    super::callbacks::CallbackContract::new("endEditing", 3),
    super::callbacks::CallbackContract::new("notifyModelUpdates", 4),
    super::callbacks::CallbackContract::new("beginRestoringDocumentFromArchive", 5),
    super::callbacks::CallbackContract::new("endRestoringDocumentFromArchive", 6),
    super::callbacks::CallbackContract::new("storeDocumentToArchive", 7),
    super::callbacks::CallbackContract::new("updateDocumentProperties", 8),
    super::callbacks::CallbackContract::new("createMusicalContext", 9),
    super::callbacks::CallbackContract::new("updateMusicalContextProperties", 10),
    super::callbacks::CallbackContract::new("updateMusicalContextContent", 11),
    super::callbacks::CallbackContract::new("destroyMusicalContext", 12),
    super::callbacks::CallbackContract::new("createAudioSource", 13),
    super::callbacks::CallbackContract::new("updateAudioSourceProperties", 14),
    super::callbacks::CallbackContract::new("updateAudioSourceContent", 15),
    super::callbacks::CallbackContract::new("enableAudioSourceSamplesAccess", 16),
    super::callbacks::CallbackContract::new("deactivateAudioSourceForUndoHistory", 17),
    super::callbacks::CallbackContract::new("destroyAudioSource", 18),
    super::callbacks::CallbackContract::new("createAudioModification", 19),
    super::callbacks::CallbackContract::new("cloneAudioModification", 20),
    super::callbacks::CallbackContract::new("updateAudioModificationProperties", 21),
    super::callbacks::CallbackContract::new("deactivateAudioModificationForUndoHistory", 22),
    super::callbacks::CallbackContract::new("destroyAudioModification", 23),
    super::callbacks::CallbackContract::new("createPlaybackRegion", 24),
    super::callbacks::CallbackContract::new("updatePlaybackRegionProperties", 25),
    super::callbacks::CallbackContract::new("destroyPlaybackRegion", 26),
    super::callbacks::CallbackContract::new("isAudioSourceContentAvailable", 27),
    super::callbacks::CallbackContract::new("isAudioSourceContentAnalysisIncomplete", 28),
    super::callbacks::CallbackContract::new("requestAudioSourceContentAnalysis", 29),
    super::callbacks::CallbackContract::new("getAudioSourceContentGrade", 30),
    super::callbacks::CallbackContract::new("createAudioSourceContentReader", 31),
    super::callbacks::CallbackContract::new("isAudioModificationContentAvailable", 32),
    super::callbacks::CallbackContract::new("getAudioModificationContentGrade", 33),
    super::callbacks::CallbackContract::new("createAudioModificationContentReader", 34),
    super::callbacks::CallbackContract::new("isPlaybackRegionContentAvailable", 35),
    super::callbacks::CallbackContract::new("getPlaybackRegionContentGrade", 36),
    super::callbacks::CallbackContract::new("createPlaybackRegionContentReader", 37),
    super::callbacks::CallbackContract::new("getContentReaderEventCount", 38),
    super::callbacks::CallbackContract::new("getContentReaderDataForEvent", 39),
    super::callbacks::CallbackContract::new("destroyContentReader", 40),
    super::callbacks::CallbackContract::new("createRegionSequence", 41),
    super::callbacks::CallbackContract::new("updateRegionSequenceProperties", 42),
    super::callbacks::CallbackContract::new("destroyRegionSequence", 43),
    super::callbacks::CallbackContract::new("getPlaybackRegionHeadAndTailTime", 44),
    super::callbacks::CallbackContract::new("restoreObjectsFromArchive", 45),
    super::callbacks::CallbackContract::new("storeObjectsToArchive", 46),
    super::callbacks::CallbackContract::new("getProcessingAlgorithmsCount", 47),
    super::callbacks::CallbackContract::new("getProcessingAlgorithmProperties", 48),
    super::callbacks::CallbackContract::new("getProcessingAlgorithmForAudioSource", 49),
    super::callbacks::CallbackContract::new("requestProcessingAlgorithmForAudioSource", 50),
    super::callbacks::CallbackContract::new("isLicensedForCapabilities", 51),
    super::callbacks::CallbackContract::new("storeAudioSourceToAudioFileChunk", 52),
    super::callbacks::CallbackContract::new("isAudioModificationPreservingAudioSourceSignal", 53),
];
