[alias]
xtask = "run --package xtask --"

[env]
ARA_SDK_DIR = { value = ".third-party/ARA_SDK", relative = true }
ARA_CLAP_DIR = { value = ".third-party/clap", relative = true }
ARA_VST3_SDK_DIR = { value = ".third-party/vst3sdk", relative = true }
