//! Raw FFI bindings for the [Celemony ARA2 SDK](https://github.com/Celemony/ARA_API).
//!
//! Generated by [`bindgen`] from `ARAInterface.h` v2.3.0.
//!
//! This crate is **not** intended to be used directly. See the [`ara-bridge`](https://docs.rs/ara2-bridge)
//! crate for safe Rust wrappers around these types.
//!
//! ## Regenerating
//!
//! The bindings are generated at build time in `build.rs`. If you update
//! `ARAInterface.h`, the bindings regenerate automatically. No manual
//! steps required.
//!
//! ## Coverage
//!
//! 210 types exported, including:
//! - 11 interface structs (function pointer vtables)
//! - Property structs for audio sources, musical contexts, region sequences
//! - Opaque reference types for plugin and host objects
//! - Constants and enums for API generations, content types, and flags
//!
//! [`bindgen`]: https://github.com/rust-lang/rust-bindgen

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/ara2_bindings.rs"));
