//! Deterministic generation of raw ARA ABI bindings.

use crate::{provenance, Mode};
use serde::Serialize;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

type DynError = Box<dyn std::error::Error>;

const SOURCE_REPOSITORY: &str = "https://github.com/Celemony/ARA_API";
const SOURCE_TAG: &str = "releases/2.3.0";
const SOURCE_COMMIT: &str = "65ec5c43b943a48cb5446f448a0492db6af8534b";
const GENERATOR: &str = "ara2-bridge xtask 0.2.0-alpha.1";
const LICENSE: &str = "Apache-2.0";
const COVERAGE_TARGET_ARG: &str = "--target=x86_64-unknown-linux-gnu";

/// One target ABI family emitted by the binding generator.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Target {
    /// Rust target triple passed to clang.
    pub triple: &'static str,
    /// Canonical generated Rust filename.
    pub filename: &'static str,
}

impl Target {
    /// Creates a target-family descriptor.
    pub const fn new(triple: &'static str, filename: &'static str) -> Self {
        Self { triple, filename }
    }
}

/// Target ABI families supported by checked-in bindings.
pub const TARGETS: &[Target] = &[
    Target::new("x86_64-unknown-linux-gnu", "x86_64.rs"),
    Target::new("aarch64-unknown-linux-gnu", "aarch64.rs"),
    Target::new("i686-pc-windows-msvc", "i686.rs"),
];

#[derive(Serialize)]
struct CoverageManifest {
    metadata: Metadata,
    core_headers: Vec<&'static str>,
    records: Vec<CoverageRecord>,
}

#[derive(Serialize)]
struct Metadata {
    source_repository: &'static str,
    source_tag: &'static str,
    normative_commit: &'static str,
    generator: &'static str,
    spdx_license: &'static str,
    notice: &'static str,
}

#[derive(Clone, Debug, Serialize)]
struct CoverageRecord {
    symbol: String,
    kind: String,
    header: String,
    span: SourceSpan,
    classification: String,
    required_sdks: Vec<String>,
}

#[derive(Clone, Debug, Serialize)]
struct SourceSpan {
    start_line: u64,
    start_column: u64,
    end_line: u64,
    end_column: u64,
}

fn message(text: impl Into<String>) -> DynError {
    std::io::Error::other(text.into()).into()
}

fn root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask is a workspace child")
}

fn metadata() -> Metadata {
    Metadata {
        source_repository: SOURCE_REPOSITORY,
        source_tag: SOURCE_TAG,
        normative_commit: SOURCE_COMMIT,
        generator: GENERATOR,
        spdx_license: LICENSE,
        notice: "DO NOT EDIT",
    }
}

pub(crate) fn rust_banner() -> String {
    format!(
        "// DO NOT EDIT: generated by {GENERATOR}.\n\
         // Source repository: {SOURCE_REPOSITORY}\n\
         // Source tag: {SOURCE_TAG}\n\
         // Normative ARA API commit: {SOURCE_COMMIT}\n\
         // Generator: {GENERATOR}\n\
         // SPDX-License-Identifier: {LICENSE}\n\n"
    )
}

/// Validates the provenance banner carried by a generated Rust derivative.
pub fn validate_generated_metadata(text: &str) -> Result<(), DynError> {
    for (field, expected) in [
        ("source repository", SOURCE_REPOSITORY),
        ("source tag", SOURCE_TAG),
        ("normative commit", SOURCE_COMMIT),
        ("generator", GENERATOR),
        ("SPDX license", LICENSE),
        ("edit notice", "DO NOT EDIT"),
    ] {
        if !text.contains(expected) {
            return Err(message(format!(
                "missing generated metadata field: {field}"
            )));
        }
    }
    Ok(())
}

/// Generates or verifies the checked-in raw bindings.
pub fn generate(mode: Mode) -> Result<(), DynError> {
    provenance::verify(root(), root().join("sdk-provenance.toml"))?;
    let api = root().join(".third-party/ARA_SDK/ARA_API");
    let generated = root().join("ara2-bridge-sys/src/generated");
    let mut coverage_bindings = None;

    for target in TARGETS {
        let output = render_bindings(&api, *target)?;
        validate_generated_metadata(&output)?;
        if output.contains(&root().display().to_string()) {
            return Err(message(format!(
                "generated bindings contain an absolute repository path for {}",
                target.triple
            )));
        }
        if target.filename == "x86_64.rs" {
            coverage_bindings = Some(output.clone());
        }
        apply(mode, &generated.join(target.filename), output.as_bytes())?;
    }

    let audio_chunks = format_rust(&render_audio_file_chunks(
        &api.join("ARAAudioFileChunks.h"),
    )?)?;
    validate_generated_metadata(&audio_chunks)?;
    apply(
        mode,
        &generated.join("audio_file_chunks.rs"),
        audio_chunks.as_bytes(),
    )?;

    let module = format_rust(&render_generated_module())?;
    validate_generated_metadata(&module)?;
    apply(mode, &generated.join("mod.rs"), module.as_bytes())?;

    let coverage = render_symbol_coverage(
        &api,
        coverage_bindings
            .as_deref()
            .ok_or_else(|| message("x86_64 coverage bindings were not generated"))?,
    )?;
    apply(
        mode,
        &root().join("ara2-bridge-sys/generated/symbol-coverage.json"),
        coverage.as_bytes(),
    )?;
    Ok(())
}

fn render_bindings(api: &Path, target: Target) -> Result<String, DynError> {
    let include = format!("-I{}", api.display());
    let target_arg = format!("--target={}", target.triple);
    let resource_include = clang_resource_include()?;
    let resource_include = resource_include.to_string_lossy();
    let bindings = bindgen::Builder::default()
        .header_contents(
            "ara2_bridge_wrapper.h",
            "#include \"ARAInterface.h\"\n#include \"ARAAudioFileChunks.h\"\n",
        )
        .clang_args([
            "-x",
            "c",
            "-std=c11",
            "-nostdinc",
            "-isystem",
            resource_include.as_ref(),
            include.as_str(),
            target_arg.as_str(),
        ])
        .allowlist_type("ARA.*")
        .allowlist_var("kARA.*")
        .allowlist_function("ARA.*")
        .blocklist_item("kARAXMLName_.*")
        .default_enum_style(bindgen::EnumVariation::Consts)
        .size_t_is_usize(true)
        .generate_comments(false)
        .layout_tests(false)
        .generate()
        .map_err(|error| message(format!("bindgen failed for {}: {error}", target.triple)))?;
    let mut bindings = bindings.to_string();
    for (generated, corrected) in [
        (
            "pub const kARAInvalidFrequency: f64 = 0.0;",
            "pub const kARAInvalidFrequency: f32 = 0.0;",
        ),
        (
            "pub const kARADefaultConcertPitchFrequency: f64 = 440.0;",
            "pub const kARADefaultConcertPitchFrequency: f32 = 440.0;",
        ),
    ] {
        if !bindings.contains(generated) {
            return Err(message(format!(
                "bindgen output no longer contains expected float macro: {generated}"
            )));
        }
        bindings = bindings.replace(generated, corrected);
    }
    Ok(format!(
        "{}{}\n\
         /// Sentinel for a note without a quantized pitch.\n\
         pub const kARAInvalidPitchNumber: ARAPitchNumber = i32::MIN;\n\
         /// Canonical false value for `ARABool`.\n\
         pub const kARAFalse: ARABool = 0;\n\
         /// Canonical true value for `ARABool`.\n\
         pub const kARATrue: ARABool = 1;\n",
        rust_banner(),
        bindings
    ))
}

fn render_audio_file_chunks(header: &Path) -> Result<String, DynError> {
    let text = std::fs::read_to_string(header)?;
    let mut constants = Vec::new();
    let mut in_c_branch = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed == "#else" {
            in_c_branch = true;
            continue;
        }
        if in_c_branch && trimmed == "#endif" {
            break;
        }
        if !in_c_branch || !trimmed.starts_with("#define kARAXMLName_") {
            continue;
        }
        let mut parts = trimmed.split_whitespace();
        let _define = parts.next();
        let name = parts
            .next()
            .ok_or_else(|| message(format!("malformed XML constant: {trimmed}")))?;
        let value = parts.collect::<Vec<_>>().join(" ");
        let value = value
            .strip_prefix('"')
            .and_then(|value| value.strip_suffix('"'))
            .ok_or_else(|| message(format!("non-string XML constant: {trimmed}")))?;
        constants.push((name.to_owned(), value.to_owned(), false));
    }

    let synthetic_name = "kARAXMLName_CreateDistinctAudioModification";
    let synthetic_value = "createDistinctAudioModification";
    let cpp_declaration = format!("constexpr auto {synthetic_name} {{ \"{synthetic_value}\" }};");
    if !text.contains(&cpp_declaration) {
        return Err(message(format!(
            "reviewed C++ XML constant changed or disappeared: {synthetic_name}"
        )));
    }
    if constants.iter().any(|(name, _, _)| name == synthetic_name) {
        return Err(message(format!(
            "{synthetic_name} is no longer C++-only; review the synthetic binding"
        )));
    }
    constants.push((synthetic_name.to_owned(), synthetic_value.to_owned(), true));

    let mut output = rust_banner();
    output.push_str("#![allow(non_upper_case_globals)]\n\n");
    for (name, value, synthetic) in constants {
        if synthetic {
            output.push_str("/// Reviewed synthetic binding for the released C++-only constant.\n");
        } else {
            output.push_str("/// XML element name defined by `ARAAudioFileChunks.h`.\n");
        }
        output.push_str(&format!("pub const {name}: &str = {value:?};\n"));
    }
    Ok(output)
}

fn render_generated_module() -> String {
    format!(
        "{}\
         #[cfg(target_arch = \"x86_64\")]\n\
         #[path = \"x86_64.rs\"]\n\
         mod target;\n\
         #[cfg(target_arch = \"aarch64\")]\n\
         #[path = \"aarch64.rs\"]\n\
         mod target;\n\
         #[cfg(all(target_arch = \"x86\", target_pointer_width = \"32\"))]\n\
         #[path = \"i686.rs\"]\n\
         mod target;\n\n\
         pub mod audio_file_chunks;\n\
         pub mod access;\n\
         pub mod compatibility;\n\
         pub mod layout;\n\
         pub use target::*;\n",
        rust_banner()
    )
}

pub(crate) fn apply(mode: Mode, path: &Path, expected: &[u8]) -> Result<(), DynError> {
    match mode {
        Mode::Check => {
            let actual = std::fs::read(path).map_err(|error| {
                message(format!(
                    "missing generated artifact {}: {error}",
                    path.display()
                ))
            })?;
            if actual != expected {
                return Err(message(format!(
                    "generated artifact is stale: {}; run `cargo xtask ara bindings --write`",
                    path.display()
                )));
            }
        }
        Mode::Write => {
            let parent = path
                .parent()
                .ok_or_else(|| message(format!("output has no parent: {}", path.display())))?;
            std::fs::create_dir_all(parent)?;
            let temporary = temporary_path(path);
            std::fs::write(&temporary, expected)?;
            std::fs::rename(&temporary, path)?;
        }
    }
    Ok(())
}

pub(crate) fn format_rust(source: &str) -> Result<String, DynError> {
    let mut child = Command::new("rustfmt")
        .args(["--emit", "stdout", "--edition", "2021"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()?;
    child
        .stdin
        .take()
        .ok_or_else(|| message("rustfmt stdin was not available"))?
        .write_all(source.as_bytes())?;
    let output = child.wait_with_output()?;
    if !output.status.success() {
        return Err(message(format!(
            "rustfmt failed for generated output: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn temporary_path(path: &Path) -> PathBuf {
    let mut name = path.as_os_str().to_owned();
    name.push(format!(".tmp-{}", std::process::id()));
    PathBuf::from(name)
}

fn render_symbol_coverage(api: &Path, raw_bindings: &str) -> Result<String, DynError> {
    let core_headers = ["ARAInterface.h", "ARAAudioFileChunks.h"];
    let mut records = Vec::new();
    for header in core_headers {
        preprocess_core_header(api, header)?;
        if header == "ARAInterface.h" {
            records.extend(ast_records(api, header)?);
        }
        records.extend(macro_records(&api.join(header), header, "core-abi", &[])?);
    }

    for (header, sdk) in [
        ("ARACLAP.h", "clap"),
        ("ARAVST3.h", "vst3"),
        ("ARAAudioUnit.h", "audio-unit"),
    ] {
        records.extend(companion_records(&api.join(header), header, sdk)?);
    }

    let mut unique = BTreeMap::new();
    for record in records {
        let key = (
            record.header.clone(),
            record.kind.clone(),
            record.symbol.clone(),
        );
        match unique.entry(key) {
            std::collections::btree_map::Entry::Vacant(entry) => {
                entry.insert(record);
            }
            std::collections::btree_map::Entry::Occupied(mut entry) => {
                if entry.get().span.start_line == 0 && record.span.start_line != 0 {
                    entry.insert(record);
                }
            }
        }
    }
    let mut records: Vec<_> = unique.into_values().collect();
    records.sort_by(|left, right| {
        (&left.header, left.span.start_line, &left.kind, &left.symbol).cmp(&(
            &right.header,
            right.span.start_line,
            &right.kind,
            &right.symbol,
        ))
    });
    if records.is_empty() {
        return Err(message("symbol coverage inventory is empty"));
    }
    for record in &records {
        if record.classification != "core-abi" && record.classification != "companion-deferred" {
            return Err(message(format!(
                "unknown symbol classification for {}",
                record.symbol
            )));
        }
        if record.classification == "companion-deferred" && record.required_sdks.is_empty() {
            return Err(message(format!(
                "companion symbol has no required SDK: {}",
                record.symbol
            )));
        }
        if record.classification == "core-abi" && !record.required_sdks.is_empty() {
            return Err(message(format!(
                "core symbol incorrectly depends on a companion SDK: {}",
                record.symbol
            )));
        }
        if record.span.start_line == 0 || record.span.start_column == 0 {
            return Err(message(format!(
                "symbol has no exact source span: {}::{}",
                record.header, record.symbol
            )));
        }
    }
    validate_binding_coverage(raw_bindings, &records)?;
    validate_companion_inventory(&records)?;

    let manifest = CoverageManifest {
        metadata: metadata(),
        core_headers: core_headers.to_vec(),
        records,
    };
    Ok(format!("{}\n", serde_json::to_string_pretty(&manifest)?))
}

fn validate_binding_coverage(
    raw_bindings: &str,
    records: &[CoverageRecord],
) -> Result<(), DynError> {
    let covered: BTreeMap<_, _> = records
        .iter()
        .filter(|record| record.classification == "core-abi")
        .map(|record| (record.symbol.as_str(), record))
        .collect();
    let mut current_struct: Option<&str> = None;
    for line in raw_bindings.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("pub struct ") {
            let name = rest.split_whitespace().next().unwrap_or("");
            current_struct = Some(name);
            if name.starts_with("ARA") && !covered.contains_key(name) {
                return Err(message(format!(
                    "generated struct is missing from symbol coverage: {name}"
                )));
            }
            continue;
        }
        if trimmed == "}" {
            current_struct = None;
            continue;
        }
        if let Some(owner) = current_struct {
            if let Some(rest) = trimmed.strip_prefix("pub ") {
                let field = rest.split(':').next().unwrap_or("");
                if !field.starts_with('_') {
                    let qualified = format!("{owner}.{field}");
                    if !covered.contains_key(qualified.as_str()) {
                        return Err(message(format!(
                            "generated field is missing from symbol coverage: {qualified}"
                        )));
                    }
                }
            }
            continue;
        }
        let name = trimmed
            .strip_prefix("pub const ")
            .or_else(|| trimmed.strip_prefix("pub type "))
            .and_then(|rest| {
                rest.split(|character: char| {
                    character == ':' || character == ' ' || character == '='
                })
                .next()
            })
            .unwrap_or("");
        if (name.starts_with("ARA") || name.starts_with("kARA")) && !covered.contains_key(name) {
            return Err(message(format!(
                "generated symbol is missing from symbol coverage: {name}"
            )));
        }
    }
    Ok(())
}

fn validate_companion_inventory(records: &[CoverageRecord]) -> Result<(), DynError> {
    let expected: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::from([
        (
            "ARACLAP.h",
            BTreeSet::from([
                "ARACLAP_h",
                "CLAP_EXT_ARA_FACTORY",
                "CLAP_EXT_ARA_FACTORY_COMPAT",
                "CLAP_EXT_ARA_PLUGINEXTENSION",
                "CLAP_EXT_ARA_PLUGINEXTENSION_COMPAT",
                "CLAP_PLUGIN_FEATURE_ARA_REQUIRED",
                "CLAP_PLUGIN_FEATURE_ARA_SUPPORTED",
                "clap_ara_factory",
                "clap_ara_factory.get_ara_factory",
                "clap_ara_factory.get_factory_count",
                "clap_ara_factory.get_plugin_id",
                "clap_ara_factory_t",
                "clap_ara_plugin_extension",
                "clap_ara_plugin_extension.bind_to_document_controller",
                "clap_ara_plugin_extension.get_factory",
                "clap_ara_plugin_extension_t",
            ]),
        ),
        (
            "ARAVST3.h",
            BTreeSet::from([
                "ARAVST3_h",
                "ARA_DISABLE_VST3_GCC_VARIANT_WARNINGS",
                "ARA_DISABLE_VST3_PRAGMA_PACK_WARNINGS",
                "ARA_DISABLE_VST3_WARNINGS_BEGIN",
                "ARA_DISABLE_VST3_WARNINGS_END",
                "IMainFactory",
                "IMainFactory.getFactory",
                "IMainFactory.iid",
                "IPlugInEntryPoint",
                "IPlugInEntryPoint.bindToDocumentController",
                "IPlugInEntryPoint.getFactory",
                "IPlugInEntryPoint.iid",
                "IPlugInEntryPoint2",
                "IPlugInEntryPoint2.bindToDocumentControllerWithRoles",
                "IPlugInEntryPoint2.iid",
                "kARAMainFactoryClass",
            ]),
        ),
        (
            "ARAAudioUnit.h",
            BTreeSet::from([
                "ARAAudioUnit_h",
                "ARAAudioUnitFactory",
                "ARAAudioUnitFactory.inOutMagicNumber",
                "ARAAudioUnitFactory.outFactory",
                "ARAAudioUnitPlugInExtensionBinding",
                "ARAAudioUnitPlugInExtensionBinding.assignedRoles",
                "ARAAudioUnitPlugInExtensionBinding.inDocumentControllerRef",
                "ARAAudioUnitPlugInExtensionBinding.inOutMagicNumber",
                "ARAAudioUnitPlugInExtensionBinding.knownRoles",
                "ARAAudioUnitPlugInExtensionBinding.outPlugInExtension",
                "kARAAudioComponentTag",
                "kARAAudioUnitMagic",
                "kAudioUnitProperty_ARAFactory",
                "kAudioUnitProperty_ARAPlugInExtensionBinding",
                "kAudioUnitProperty_ARAPlugInExtensionBindingWithRoles",
            ]),
        ),
    ]);

    for (header, expected_symbols) in expected {
        let actual: BTreeSet<_> = records
            .iter()
            .filter(|record| {
                record.header == header && record.classification == "companion-deferred"
            })
            .map(|record| record.symbol.as_str())
            .collect();
        if actual != expected_symbols {
            let missing: Vec<_> = expected_symbols.difference(&actual).copied().collect();
            let unexpected: Vec<_> = actual.difference(&expected_symbols).copied().collect();
            return Err(message(format!(
                "companion inventory mismatch for {header}; missing={missing:?}, unexpected={unexpected:?}"
            )));
        }
    }
    Ok(())
}

fn clang() -> String {
    std::env::var("CLANG").unwrap_or_else(|_| "clang".to_owned())
}

fn clang_resource_include() -> Result<PathBuf, DynError> {
    let output = Command::new(clang()).arg("-print-resource-dir").output()?;
    if !output.status.success() {
        return Err(message(format!(
            "could not locate clang resource headers: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let directory = PathBuf::from(String::from_utf8(output.stdout)?.trim()).join("include");
    if !directory.is_dir() {
        return Err(message(format!(
            "clang resource include directory does not exist: {}",
            directory.display()
        )));
    }
    Ok(directory)
}

fn preprocess_core_header(api: &Path, header: &str) -> Result<(), DynError> {
    let output = Command::new(clang())
        .current_dir(api)
        .args([
            COVERAGE_TARGET_ARG,
            "-E",
            "-dD",
            "-x",
            "c",
            "-std=c11",
            header,
        ])
        .output()?;
    if !output.status.success() {
        return Err(message(format!(
            "could not preprocess {header}: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    if output.stdout.is_empty() {
        return Err(message(format!(
            "preprocessor produced no output for {header}"
        )));
    }
    Ok(())
}

fn ast_records(api: &Path, header: &str) -> Result<Vec<CoverageRecord>, DynError> {
    let output = Command::new(clang())
        .current_dir(api)
        .args([
            COVERAGE_TARGET_ARG,
            "-x",
            "c",
            "-std=c11",
            "-Xclang",
            "-ast-dump=json",
            "-fsyntax-only",
            header,
        ])
        .output()?;
    if !output.status.success() {
        return Err(message(format!(
            "could not inspect declarations in {header}: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let ast: Value = serde_json::from_slice(&output.stdout)?;
    let mut records = Vec::new();
    walk_ast(&ast, header, None, &mut records);
    let source = std::fs::read_to_string(api.join(header))?;
    for record in &mut records {
        if record.span.start_line == 0 {
            if let Some((line, column)) = find_source_token(&source, &record.symbol) {
                record.span = SourceSpan {
                    start_line: line,
                    start_column: column,
                    end_line: line,
                    end_column: column + record.symbol.len() as u64,
                };
            }
        }
    }
    Ok(records)
}

fn find_source_token(source: &str, qualified_symbol: &str) -> Option<(u64, u64)> {
    let symbol = qualified_symbol
        .rsplit('.')
        .next()
        .unwrap_or(qualified_symbol);
    source.lines().enumerate().find_map(|(index, line)| {
        line.find(symbol)
            .map(|column| (index as u64 + 1, column as u64 + 1))
    })
}

fn walk_ast(
    node: &Value,
    header: &str,
    parent_record: Option<&str>,
    records: &mut Vec<CoverageRecord>,
) {
    let kind = node.get("kind").and_then(Value::as_str).unwrap_or("");
    let name = node.get("name").and_then(Value::as_str).unwrap_or("");
    let mut child_parent = parent_record;

    match kind {
        "RecordDecl" if name.starts_with("ARA") => {
            let complete = node.get("completeDefinition") == Some(&Value::Bool(true));
            push_ast_record(
                records,
                node,
                name,
                if complete { "struct" } else { "opaque-struct" },
                header,
            );
            if complete {
                child_parent = Some(name);
            }
        }
        "FieldDecl" => {
            if let Some(parent) = parent_record {
                if !name.is_empty() {
                    push_ast_record(records, node, &format!("{parent}.{name}"), "field", header);
                }
            }
        }
        "TypedefDecl" if name.starts_with("ARA") => {
            let qualified = node
                .get("type")
                .and_then(|value| value.get("qualType"))
                .and_then(Value::as_str)
                .unwrap_or("");
            let kind = if qualified.contains("(*)") || qualified.contains("(*)(") {
                "callback"
            } else {
                "typedef"
            };
            push_ast_record(records, node, name, kind, header);
        }
        "EnumDecl" if name.starts_with("ARA") => {
            push_ast_record(records, node, name, "enum", header);
        }
        "EnumConstantDecl" if name.starts_with("kARA") || name.starts_with("ARA") => {
            push_ast_record(records, node, name, "constant", header);
        }
        "FunctionDecl" if name.starts_with("ARA") => {
            push_ast_record(records, node, name, "function", header);
        }
        "VarDecl" if name.starts_with("kARA") || name.starts_with("ARA") => {
            push_ast_record(records, node, name, "constant", header);
        }
        _ => {}
    }

    if let Some(children) = node.get("inner").and_then(Value::as_array) {
        for child in children {
            walk_ast(child, header, child_parent, records);
        }
    }
}

fn push_ast_record(
    records: &mut Vec<CoverageRecord>,
    node: &Value,
    symbol: &str,
    kind: &str,
    header: &str,
) {
    let (line, column) = node.get("loc").and_then(ast_line_column).unwrap_or((0, 0));
    let end = node.get("range").and_then(|range| range.get("end"));
    records.push(CoverageRecord {
        symbol: symbol.to_owned(),
        kind: kind.to_owned(),
        header: header.to_owned(),
        span: SourceSpan {
            start_line: line,
            start_column: column,
            end_line: end.and_then(ast_line_column).map_or(line, |value| value.0),
            end_column: end
                .and_then(ast_line_column)
                .map_or(column, |value| value.1),
        },
        classification: "core-abi".to_owned(),
        required_sdks: Vec::new(),
    });
}

fn ast_line_column(location: &Value) -> Option<(u64, u64)> {
    let selected = if location.get("line").is_some() {
        location
    } else {
        location
            .get("expansionLoc")
            .or_else(|| location.get("spellingLoc"))?
    };
    Some((
        selected.get("line")?.as_u64()?,
        selected.get("col")?.as_u64()?,
    ))
}

fn macro_records(
    path: &Path,
    header: &str,
    classification: &str,
    required_sdks: &[&str],
) -> Result<Vec<CoverageRecord>, DynError> {
    let text = std::fs::read_to_string(path)?;
    let mut records = Vec::new();
    for (index, line) in text.lines().enumerate() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix("#define") else {
            continue;
        };
        let rest = remove_inline_block_comments(rest);
        let name = rest
            .trim_start()
            .split(|character: char| character.is_whitespace() || character == '(')
            .next()
            .unwrap_or("");
        if !(name.starts_with("ARA") || name.starts_with("kARA") || name.contains("_ARA")) {
            continue;
        }
        let column = line.find(name).unwrap_or(0) as u64 + 1;
        records.push(CoverageRecord {
            symbol: name.to_owned(),
            kind: "macro".to_owned(),
            header: header.to_owned(),
            span: SourceSpan {
                start_line: index as u64 + 1,
                start_column: column,
                end_line: index as u64 + 1,
                end_column: column + name.len() as u64,
            },
            classification: classification.to_owned(),
            required_sdks: required_sdks.iter().map(|sdk| (*sdk).to_owned()).collect(),
        });
    }
    Ok(records)
}

fn remove_inline_block_comments(text: &str) -> String {
    let mut output = String::new();
    let mut remaining = text;
    while let Some(start) = remaining.find("/*") {
        output.push_str(&remaining[..start]);
        let Some(end) = remaining[start + 2..].find("*/") else {
            return output;
        };
        remaining = &remaining[start + 2 + end + 2..];
    }
    output.push_str(remaining);
    output
}

fn companion_records(
    path: &Path,
    header: &str,
    sdk: &str,
) -> Result<Vec<CoverageRecord>, DynError> {
    let text = std::fs::read_to_string(path)?;
    let lines: Vec<_> = text.lines().collect();
    let mut records = macro_records(path, header, "companion-deferred", &[sdk])?;
    match header {
        "ARACLAP.h" => inventory_clap(&lines, header, sdk, &mut records),
        "ARAVST3.h" => inventory_vst3(&lines, header, sdk, &mut records),
        "ARAAudioUnit.h" => inventory_audio_unit(&lines, header, sdk, &mut records),
        _ => return Err(message(format!("unknown companion header: {header}"))),
    }
    Ok(records)
}

fn identifiers(text: &str) -> Vec<&str> {
    text.split(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
        .filter(|token| {
            !token.is_empty()
                && token
                    .as_bytes()
                    .first()
                    .is_some_and(|byte| byte.is_ascii_alphabetic() || *byte == b'_')
        })
        .collect()
}

fn inventory_clap(lines: &[&str], header: &str, sdk: &str, records: &mut Vec<CoverageRecord>) {
    let mut owner: Option<String> = None;
    let mut statement = String::new();
    let mut statement_start = 0;
    for (index, line) in lines.iter().enumerate() {
        let line_number = index as u64 + 1;
        let trimmed = line.trim();
        if trimmed.contains("CLAP_CONSTEXPR const char") {
            if let Some(name) = trimmed
                .split_once("const char")
                .and_then(|(_, rest)| rest.split('[').next())
                .map(str::trim)
            {
                push_companion(
                    records,
                    lines,
                    name,
                    "constant",
                    header,
                    line_number,
                    line_number,
                    sdk,
                );
            }
        }
        if trimmed.starts_with("typedef struct ") {
            if let Some(name) = identifiers(trimmed).last() {
                owner = Some((*name).to_owned());
                push_companion(
                    records,
                    lines,
                    name,
                    "struct",
                    header,
                    line_number,
                    line_number,
                    sdk,
                );
            }
            statement.clear();
            continue;
        }
        let Some(current_owner) = owner.as_ref() else {
            continue;
        };
        if trimmed.starts_with('}') {
            if let Some(alias) = identifiers(trimmed).first() {
                push_companion(
                    records,
                    lines,
                    alias,
                    "typedef",
                    header,
                    line_number,
                    line_number,
                    sdk,
                );
            }
            owner = None;
            statement.clear();
            continue;
        }
        if trimmed == "{" || trimmed.is_empty() || trimmed.starts_with("//") {
            continue;
        }
        if statement.is_empty() {
            statement_start = line_number;
        }
        statement.push(' ');
        statement.push_str(trimmed);
        if !trimmed.contains(';') {
            continue;
        }
        if let Some(marker) = statement.find("CLAP_ABI") {
            if let Some(star) = statement[marker..].find('*') {
                if let Some(name) = identifiers(&statement[marker + star + 1..]).first() {
                    let symbol = format!("{current_owner}.{name}");
                    push_companion(
                        records,
                        lines,
                        &symbol,
                        "field",
                        header,
                        statement_start,
                        line_number,
                        sdk,
                    );
                }
            }
        }
        statement.clear();
    }
}

fn inventory_vst3(lines: &[&str], header: &str, sdk: &str, records: &mut Vec<CoverageRecord>) {
    let mut owner: Option<String> = None;
    let mut statement = String::new();
    let mut statement_start = 0;
    for (index, line) in lines.iter().enumerate() {
        let line_number = index as u64 + 1;
        let trimmed = line.trim();
        if trimmed.starts_with("class ") {
            let before_base = trimmed.split(':').next().unwrap_or(trimmed);
            if let Some(name) = identifiers(before_base).last() {
                owner = Some((*name).to_owned());
                push_companion(
                    records,
                    lines,
                    name,
                    "class",
                    header,
                    line_number,
                    line_number,
                    sdk,
                );
            }
            continue;
        }
        let Some(current_owner) = owner.as_ref() else {
            continue;
        };
        if trimmed == "};" {
            owner = None;
            statement.clear();
            continue;
        }
        if trimmed.contains("static const Steinberg::FUID iid") {
            let symbol = format!("{current_owner}.iid");
            push_companion(
                records,
                lines,
                &symbol,
                "field",
                header,
                line_number,
                line_number,
                sdk,
            );
        }
        if statement.is_empty() && !trimmed.contains("virtual ") {
            continue;
        }
        if statement.is_empty() {
            statement_start = line_number;
        }
        statement.push(' ');
        statement.push_str(trimmed);
        if !trimmed.contains(';') {
            continue;
        }
        if let Some((_, after_api)) = statement.split_once("PLUGIN_API") {
            if let Some(before_parameters) = after_api.split('(').next() {
                if let Some(name) = identifiers(before_parameters).last() {
                    let symbol = format!("{current_owner}.{name}");
                    push_companion(
                        records,
                        lines,
                        &symbol,
                        "method",
                        header,
                        statement_start,
                        line_number,
                        sdk,
                    );
                }
            }
        }
        statement.clear();
    }
}

fn inventory_audio_unit(
    lines: &[&str],
    header: &str,
    sdk: &str,
    records: &mut Vec<CoverageRecord>,
) {
    let mut owner: Option<String> = None;
    for (index, line) in lines.iter().enumerate() {
        let line_number = index as u64 + 1;
        let trimmed = line.trim();
        if trimmed.starts_with("typedef struct ") {
            if let Some(name) = identifiers(trimmed).last() {
                owner = Some((*name).to_owned());
                push_companion(
                    records,
                    lines,
                    name,
                    "struct",
                    header,
                    line_number,
                    line_number,
                    sdk,
                );
            }
            continue;
        }
        if let Some(current_owner) = owner.as_ref() {
            if trimmed.starts_with('}') {
                if let Some(alias) = identifiers(trimmed).first() {
                    push_companion(
                        records,
                        lines,
                        alias,
                        "typedef",
                        header,
                        line_number,
                        line_number,
                        sdk,
                    );
                }
                owner = None;
                continue;
            }
            if trimmed.ends_with(';') && !trimmed.starts_with("//") {
                if let Some(name) = identifiers(trimmed).last() {
                    let symbol = format!("{current_owner}.{name}");
                    push_companion(
                        records,
                        lines,
                        &symbol,
                        "field",
                        header,
                        line_number,
                        line_number,
                        sdk,
                    );
                }
            }
        }
        if trimmed.contains('=') {
            if let Some(name) = identifiers(trimmed)
                .into_iter()
                .find(|name| name.starts_with("kARA") || name.starts_with("kAudioUnitProperty_ARA"))
            {
                push_companion(
                    records,
                    lines,
                    name,
                    "constant",
                    header,
                    line_number,
                    line_number,
                    sdk,
                );
            }
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn push_companion(
    records: &mut Vec<CoverageRecord>,
    lines: &[&str],
    symbol: &str,
    kind: &str,
    header: &str,
    start_line: u64,
    end_line: u64,
    sdk: &str,
) {
    let leaf = symbol.rsplit('.').next().unwrap_or(symbol);
    let mut exact_line = start_line;
    let mut column = 1;
    for line_number in start_line..=end_line {
        if let Some(found) = lines[(line_number - 1) as usize].find(leaf) {
            exact_line = line_number;
            column = found as u64 + 1;
            break;
        }
    }
    records.push(CoverageRecord {
        symbol: symbol.to_owned(),
        kind: kind.to_owned(),
        header: header.to_owned(),
        span: SourceSpan {
            start_line: exact_line,
            start_column: column,
            end_line,
            end_column: column + leaf.len() as u64,
        },
        classification: "companion-deferred".to_owned(),
        required_sdks: vec![sdk.to_owned()],
    });
}
