//! Maintainer commands for generating and validating ARA bridge artifacts.

pub mod ara;
pub mod bindings;
pub mod ci;
pub mod companion_probe;
pub mod compatibility;
pub mod core_probe;
pub mod coverage;
pub mod docs;
pub mod fixtures;
pub mod fuzz_corpus;
pub mod host_dispatch;
pub mod plugin_dispatch;
pub mod provenance;
pub mod release;

/// Whether a generator verifies checked-in output or rewrites it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Mode {
    /// Compare generated bytes with the checked-in artifacts.
    Check,
    /// Write freshly generated artifacts to their canonical paths.
    Write,
}

/// Runs the maintainer command represented by `args`.
pub fn run(args: impl IntoIterator<Item = String>) -> Result<(), String> {
    let mut args = args.into_iter();
    match args.next().as_deref() {
        Some("ara") => ara::run(args),
        Some("ci") => ci::run(args),
        Some("docs") => docs::run(args),
        Some("release") => release::run(args),
        Some(command) => Err(format!("unknown xtask command: {command}")),
        None => Err("expected an xtask command (try `ara`, `ci`, `docs`, or `release`)".to_owned()),
    }
}
